### ISSUE TITLE
consult-company-narrow incorrect default value

### ISSUE THREAD

**Issue by yherve** [mohkale/consult-company#10]
Hi,
I have the following list for consult-company-narrow and if no match is found, it seems to use the first in alphabetical order which is 'Classes' in my case instead of the entry corresponding to 't'

sidenote: this filtering/grouping feature is really awesome, IMO it deserves an example and a more detailed explanation in the readme

``` lisp
 '(consult-company-narrow
   '((function 102 . "Functions")
     (constant 67 . "Constants")
     (class 99 . "Classes")
     (variable 118 . "Variables")
     (color 35 . "Color")
     ((file folder)
      102 . "Files")
     (text 119 . "Word")
     (snippet 115 . "Snippet")
     (t 99 . "Completion")
```

**Comment by mohkale** [comment]
> it seems to use the first in alphabetical order which is 'Classes' in my case instead of the entry corresponding to 't'

Please share some more details about what you're doing, just from this description I'm not sure what you're trying to do as oppose to what you expect to happen.

> sidenote: this filtering/grouping feature is really awesome, IMO it deserves an example and a more detailed explanation in the readme

It isn't documented very well atm cause I kinda hate the format of the customization option. I'll likely make it much clearer later and deprecate the old variable in a later version.

**Comment by yherve** [comment]
To reproduce the problem:
- install the consult-company-narrow that I have provided above
- navigate to any place that offers completion with a category not listed. For example in the screenshot, a python buffer without context provides me a list of keywords
- as shown in the screenshot, it categorizes any items not present in consult-company-narrow under 'Classes' instead of 'Completion' (I believe it takes the first category in alphabetical order)

![Screenshot from 2023-06-13 08-02-39](https://github.com/mohkale/consult-company/assets/4946805/38d47ea5-9f4f-4692-8d33-a09e24b3182e)

Now I understand why you didn't document it more in the readme. It is not that bad though (I managed to use it with my very very limited lisp skills). The annoying thing is that it replaces the '?c' with numerical value.

**Comment by mohkale** [comment]
@yherve 

I see what you mean now. This is because of 2 reasons:

1. We don't presort candidates. The order in which the company UI shows a candidate matches the order we pass to consult and that's what's eventually shown in your completion ui.
2. I believe vertico (that looks like what you're using) groups in order of candidates so if the top candidate is a class then vertico will create a group for class and show it first. This means if the second candidate is a completion it won't show up until the second group even if in the company ui it was the second entry.

There's nothing I'd really like to do for this. You could try disabling grouping altogether (you can still narrow, you're completion ui just won't group classes together visually) by setting `(setq consult-company-group-by-kind nil)`. You could also try setting a custom sort function with `consult-customize` that always places completions on top. Honestly I don't think any solution is really ideal here, I'm of the mindset of either disabling grouping or accepting this inconsistency and adding a narrow key to get to regular completions if you find it necessary often enough.

**Comment by mohkale** [comment]
Closing as won't do. Feel free to reopen if you have any questions.
